name: stateful_ai
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^3.13.0
  firebase_auth: ^5.5.4
  google_sign_in: ^6.3.0
  flutter_bloc: ^9.1.1
  http: ^1.4.0
  flutter_dotenv: ^5.1.0
  get_it: ^7.6.4
  cupertino_icons: ^1.0.8
  cloud_firestore: ^5.6.10
  google_generative_ai: ^0.4.7
  firebase_storage: ^12.4.9
  image_picker: ^1.1.2
  flutter_markdown: ^0.7.7+1
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - .env

  uses-material-design: true
