// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCU2Fv0YiP547neKaDluJ4NMQJZjHgll80',
    appId: '1:901033106093:web:b9b39f40dd74fb2e2f0424',
    messagingSenderId: '901033106093',
    projectId: 'stateful-ai',
    authDomain: 'stateful-ai.firebaseapp.com',
    storageBucket: 'stateful-ai.firebasestorage.app',
    measurementId: 'G-3KQWNKH2VB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPfit0Dp6vPcsutsKJwCTJQcg2GDoRm7A',
    appId: '1:901033106093:android:87635f6e92cd222a2f0424',
    messagingSenderId: '901033106093',
    projectId: 'stateful-ai',
    storageBucket: 'stateful-ai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcZf7GQd5rY01vCywTmA8ezMdeGYe9crc',
    appId: '1:901033106093:ios:11d313cdad56e4462f0424',
    messagingSenderId: '901033106093',
    projectId: 'stateful-ai',
    storageBucket: 'stateful-ai.firebasestorage.app',
    androidClientId:
        '901033106093-i8q1mfr9enssiv5cli3ccfv88temr9dr.apps.googleusercontent.com',
    iosClientId:
        '901033106093-8n2td2hakbeguh695q9o7lppm2kk9riu.apps.googleusercontent.com',
    iosBundleId: 'com.project.statefulAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcZf7GQd5rY01vCywTmA8ezMdeGYe9crc',
    appId: '1:901033106093:ios:11d313cdad56e4462f0424',
    messagingSenderId: '901033106093',
    projectId: 'stateful-ai',
    storageBucket: 'stateful-ai.firebasestorage.app',
    androidClientId:
        '901033106093-i8q1mfr9enssiv5cli3ccfv88temr9dr.apps.googleusercontent.com',
    iosClientId:
        '901033106093-8n2td2hakbeguh695q9o7lppm2kk9riu.apps.googleusercontent.com',
    iosBundleId: 'com.project.statefulAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCU2Fv0YiP547neKaDluJ4NMQJZjHgll80',
    appId: '1:901033106093:web:b8e059b7a1ddf2e42f0424',
    messagingSenderId: '901033106093',
    projectId: 'stateful-ai',
    authDomain: 'stateful-ai.firebaseapp.com',
    storageBucket: 'stateful-ai.firebasestorage.app',
    measurementId: 'G-KPLCPCTTBD',
  );
}
